// Botania Recipes
const BOTANIA_RECIPES = {
    // Basic items
    "mystical_flower": { 
        name: "Mystical Flower", 
        ingredients: null, 
        category: "raw",
        note: "Found naturally, generates mana" 
    },
    "petal_apothecary": { 
        name: "Petal Apothecary", 
        ingredients: [{ item: "cobblestone", count: 5 }], 
        category: "botania",
        note: "Used to craft magical flowers with petals" 
    },
    "livingrock": { 
        name: "Livingrock", 
        ingredients: [{ item: "stone", count: 1 }], 
        category: "botania",
        note: "Created by mana infusion" 
    },
    "livingwood": { 
        name: "Livingwood", 
        ingredients: [{ item: "oak_log", count: 1 }], 
        category: "botania",
        note: "Created by mana infusion" 
    },
    "mana_pearl": { 
        name: "Mana Pearl", 
        ingredients: [{ item: "ender_pearl", count: 1 }], 
        category: "botania",
        note: "Created by mana infusion" 
    },
    "mana_diamond": { 
        name: "Mana Diamond", 
        ingredients: [{ item: "diamond", count: 1 }], 
        category: "botania",
        note: "Created by mana infusion" 
    },
    "mana_steel_ingot": { 
        name: "Manasteel Ingot", 
        ingredients: [{ item: "iron_ingot", count: 1 }], 
        category: "botania",
        note: "Created by mana infusion" 
    },
    
    // Mana generation
    "mana_pool": { 
        name: "Mana Pool", 
        ingredients: [{ item: "livingrock", count: 5 }], 
        category: "botania",
        note: "Stores mana generated by flowers" 
    },
    "diluted_mana_pool": { 
        name: "Diluted Mana Pool", 
        ingredients: [{ item: "livingrock", count: 5 }], 
        category: "botania",
        note: "Holds 10% of normal pool" 
    },
    "mana_spreader": { 
        name: "Mana Spreader", 
        ingredients: [
            { item: "livingwood", count: 7 }, 
            { item: "mana_pearl", count: 1 }
        ], 
        category: "botania",
        note: "Transfers mana from flowers to pools" 
    },
    "endoflame": { 
        name: "Endoflame", 
        ingredients: [
            { item: "mystical_flower", count: 4 }, 
            { item: "redstone", count: 1 }
        ], 
        category: "botania",
        note: "Burns nearby items to generate mana" 
    },
    "hydroangeas": { 
        name: "Hydroangeas", 
        ingredients: [
            { item: "mystical_flower", count: 4 }, 
            { item: "sugar_cane", count: 1 }
        ], 
        category: "botania",
        note: "Consumes water to generate mana" 
    },
    
    // Tools
    "lexicon_botania": { 
        name: "Lexica Botania", 
        ingredients: [{ item: "book", count: 1 }], 
        category: "botania",
        note: "Knowledge book for Botania" 
    },
    "wand_of_the_forest": { 
        name: "Wand of the Forest", 
        ingredients: [
            { item: "livingwood", count: 5 }, 
            { item: "mana_pearl", count: 1 }
        ], 
        category: "botania",
        note: "Binds flowers, shows mana levels" 
    },
    "mana_tablet": { 
        name: "Mana Tablet", 
        ingredients: [
            { item: "mana_steel_ingot", count: 5 }, 
            { item: "livingrock", count: 2 }
        ], 
        category: "botania",
        note: "Portable mana storage" 
    },
    "terrasteel_ingot": { 
        name: "Terrasteel Ingot", 
        ingredients: [
            { item: "mana_steel_ingot", count: 1 }, 
            { item: "mana_pearl", count: 1 }, 
            { item: "mana_diamond", count: 1 }
        ], 
        category: "botania",
        note: "Advanced alloy via terrestrial agglomeration plate" 
    },
};
